import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth/auth';
import { renderLabelPreviewWithMeta } from '@/lib/services/labelService';
import { handleApiError } from '@/lib/utils/errors';

/**
 * POST /api/labels/preview
 * 
 * Render a label preview with metadata
 * 
 * Request body:
 * - versionId: string (required)
 * - qrScale?: number (0.1-1.5)
 * - qrOffsetX?: number
 * - qrOffsetY?: number
 * - labelWidthIn?: number (optional size override)
 * - labelHeightIn?: number (optional size override)
 * - format?: 'json' | 'svg' (default: 'json')
 * 
 * Response (format=json):
 * {
 *   svg: string,
 *   meta: {
 *     widthIn: number,
 *     heightIn: number,
 *     hasPlaceholder: boolean,
 *     placeholderBox: { x, y, width, height } | null,
 *     isAutoGenerated: boolean
 *   }
 * }
 * 
 * Response (format=svg):
 * Raw SVG content with Content-Type: image/svg+xml
 */
export async function POST(req: Request) {
  try {
    const session = await auth();
    
    if (!session || !session.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await req.json();
    const { versionId, qrScale, qrOffsetX, qrOffsetY, labelWidthIn, labelHeightIn, contentOffsetX, contentOffsetY, contentScale, format = 'json' } = body;

    if (!versionId) {
      return NextResponse.json(
        { error: 'versionId is required' },
        { status: 400 }
      );
    }

    // Build overrides object for live preview
    const overrides: { 
      qrScale?: number; 
      qrOffsetX?: number; 
      qrOffsetY?: number;
      labelWidthIn?: number;
      labelHeightIn?: number;
      contentOffsetX?: number;
      contentOffsetY?: number;
      contentScale?: number;
    } = {};
    
    if (qrScale !== undefined) {
      const parsedScale = parseFloat(qrScale);
      if (!isNaN(parsedScale) && parsedScale >= 0.1 && parsedScale <= 1.5) {
        overrides.qrScale = parsedScale;
      }
    }
    
    if (qrOffsetX !== undefined) {
      const parsedX = parseFloat(qrOffsetX);
      if (!isNaN(parsedX)) {
        overrides.qrOffsetX = parsedX;
      }
    }
    
    if (qrOffsetY !== undefined) {
      const parsedY = parseFloat(qrOffsetY);
      if (!isNaN(parsedY)) {
        overrides.qrOffsetY = parsedY;
      }
    }

    // Label size override (render-time only, non-destructive)
    if (labelWidthIn !== undefined) {
      const parsedWidth = parseFloat(labelWidthIn);
      if (!isNaN(parsedWidth) && parsedWidth > 0 && parsedWidth <= 20) {
        overrides.labelWidthIn = parsedWidth;
      }
    }

    if (labelHeightIn !== undefined) {
      const parsedHeight = parseFloat(labelHeightIn);
      if (!isNaN(parsedHeight) && parsedHeight > 0 && parsedHeight <= 20) {
        overrides.labelHeightIn = parsedHeight;
      }
    }

    if (contentOffsetX !== undefined) {
      const parsedX = parseFloat(contentOffsetX);
      if (!isNaN(parsedX)) {
        overrides.contentOffsetX = parsedX;
      }
    }

    if (contentOffsetY !== undefined) {
      const parsedY = parseFloat(contentOffsetY);
      if (!isNaN(parsedY)) {
        overrides.contentOffsetY = parsedY;
      }
    }

    if (contentScale !== undefined) {
      const parsedScale = parseFloat(contentScale);
      if (!isNaN(parsedScale) && parsedScale > 0.1 && parsedScale <= 5.0) {
        overrides.contentScale = parsedScale;
      }
    }

    const result = await renderLabelPreviewWithMeta(
      versionId, 
      Object.keys(overrides).length > 0 ? overrides : undefined
    );

    // Support legacy format=svg for backwards compatibility
    if (format === 'svg') {
      return new NextResponse(result.svg, {
      headers: { 'Content-Type': 'image/svg+xml' }
    });
    }

    // Default: return JSON with both SVG and metadata
    return NextResponse.json(result);
  } catch (error) {
    return handleApiError(error);
  }
}

