'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import QRBoxOverlay from './QRBoxOverlay';
import {
  suggestQrPlacement,
  calculateMaxQrSize,
  findLargestEmptyRegion,
  qrBoxToOffsetScale,
  offsetScaleToQrBox,
  type QrBoxPosition,
} from '@/lib/utils/qrPlacement';

interface LabelPreviewButtonProps {
  versionId: string;
  entityType: string;
  initialQrScale?: number;
  initialQrOffsetX?: number;
  initialQrOffsetY?: number;
}

type PreviewMode = 'single' | 'sheet';

interface LabelMetadata {
  widthIn: number;
  heightIn: number;
  hasPlaceholder: boolean;
  placeholderBox: { x: number; y: number; width: number; height: number } | null;
  isAutoGenerated: boolean;
}

export default function LabelPreviewButton({ 
  versionId, 
  entityType,
  initialQrScale = 1.0,
  initialQrOffsetX = 0,
  initialQrOffsetY = 0
}: LabelPreviewButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [svgContent, setSvgContent] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  // Preview mode state
  const [previewMode, setPreviewMode] = useState<PreviewMode>('single');
  const [quantity, setQuantity] = useState(12);
  const [sheetMeta, setSheetMeta] = useState<{
    columns: number;
    rows: number;
    perSheet: number;
    rotationUsed: boolean;
    totalSheets: number;
  } | null>(null);
  
  // Label metadata from preview API
  const [labelMeta, setLabelMeta] = useState<LabelMetadata | null>(null);
  
  // Label size override state (preview-only, non-destructive)
  const [labelSizeOverride, setLabelSizeOverride] = useState(false);
  const [labelWidthIn, setLabelWidthIn] = useState<number>(2);
  const [labelHeightIn, setLabelHeightIn] = useState<number>(2);
  const [nativeLabelWidthIn, setNativeLabelWidthIn] = useState<number | null>(null);
  const [nativeLabelHeightIn, setNativeLabelHeightIn] = useState<number | null>(null);
  const [labelSizeUnit, setLabelSizeUnit] = useState<'in' | 'mm'>('in');
  
  // Content placement state (preview-only, non-destructive)
  const [contentOffsetX, setContentOffsetX] = useState(0);
  const [contentOffsetY, setContentOffsetY] = useState(0);
  const [contentScale, setContentScale] = useState(1.0);
  
  // Controls precision state
  const [useFineControls, setUseFineControls] = useState(false);
  
  // QR Position state (offset/scale for API compatibility)
  const [qrScale, setQrScale] = useState(initialQrScale);
  const [qrOffsetX, setQrOffsetX] = useState(initialQrOffsetX);
  const [qrOffsetY, setQrOffsetY] = useState(initialQrOffsetY);
  
  // QR Box state (absolute position - primary editing model)
  const [qrBox, setQrBox] = useState<QrBoxPosition | null>(null);
  const [showSuggestions, setShowSuggestions] = useState(false);
  
  // Saved values
  const [savedQrScale, setSavedQrScale] = useState(initialQrScale);
  const [savedQrOffsetX, setSavedQrOffsetX] = useState(initialQrOffsetX);
  const [savedQrOffsetY, setSavedQrOffsetY] = useState(initialQrOffsetY);
  
  // Saved canvas values
  const [savedLabelWidthIn, setSavedLabelWidthIn] = useState<number | null>(null);
  const [savedLabelHeightIn, setSavedLabelHeightIn] = useState<number | null>(null);
  const [savedContentScale, setSavedContentScale] = useState(1.0);
  const [savedContentOffsetX, setSavedContentOffsetX] = useState(0);
  const [savedContentOffsetY, setSavedContentOffsetY] = useState(0);
  
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);

  // Container ref for QR overlay positioning
  const previewContainerRef = useRef<HTMLDivElement>(null);
  const [containerDimensions, setContainerDimensions] = useState({ width: 0, height: 0 });

  // Unit conversion helpers
  const inToMm = (inches: number) => inches * 25.4;
  const mmToIn = (mm: number) => mm / 25.4;

  // Track if values have changed from saved values
  useEffect(() => {
    const isQrChanged = 
      qrScale !== savedQrScale || 
      qrOffsetX !== savedQrOffsetX || 
      qrOffsetY !== savedQrOffsetY;

    const isCanvasChanged = 
      Math.abs(contentScale - savedContentScale) > 0.001 ||
      Math.abs(contentOffsetX - savedContentOffsetX) > 0.001 ||
      Math.abs(contentOffsetY - savedContentOffsetY) > 0.001;

    const isSizeChanged = labelSizeOverride 
      ? (savedLabelWidthIn !== null && Math.abs(labelWidthIn - savedLabelWidthIn) > 0.001) ||
        (savedLabelHeightIn !== null && Math.abs(labelHeightIn - savedLabelHeightIn) > 0.001) ||
        (savedLabelWidthIn === null) // Changed from native to override
      : savedLabelWidthIn !== null; // Changed from override to native (if saved had override)

    setHasUnsavedChanges(isQrChanged || isCanvasChanged || isSizeChanged);
  }, [
    qrScale, qrOffsetX, qrOffsetY, 
    contentScale, contentOffsetX, contentOffsetY,
    labelWidthIn, labelHeightIn, labelSizeOverride,
    savedQrScale, savedQrOffsetX, savedQrOffsetY,
    savedContentScale, savedContentOffsetX, savedContentOffsetY,
    savedLabelWidthIn, savedLabelHeightIn
  ]);

  // Measure container dimensions for QR overlay
  useEffect(() => {
    if (!previewContainerRef.current || !svgContent) return;
    
    const updateDimensions = () => {
      if (previewContainerRef.current) {
        const svg = previewContainerRef.current.querySelector('svg');
        if (svg) {
          const rect = svg.getBoundingClientRect();
          setContainerDimensions({ width: rect.width, height: rect.height });
        }
      }
    };
    
    // Initial measurement
    updateDimensions();
    
    // Re-measure on resize
    const resizeObserver = new ResizeObserver(updateDimensions);
    if (previewContainerRef.current) {
      resizeObserver.observe(previewContainerRef.current);
    }
    
    return () => resizeObserver.disconnect();
  }, [svgContent]);

  // Initialize qrBox from offset/scale when labelMeta is available
  useEffect(() => {
    if (!labelMeta?.placeholderBox) return;
    
    // If user has never positioned QR (all defaults), suggest smart placement
    const isDefault = qrScale === 1.0 && qrOffsetX === 0 && qrOffsetY === 0;
    
    if (isDefault && labelMeta.isAutoGenerated) {
      // Use smart placement for auto-generated placeholders
      const suggested = suggestQrPlacement({
        labelWidthIn: labelMeta.widthIn,
        labelHeightIn: labelMeta.heightIn,
      });
      setQrBox(suggested);
    } else {
      // Convert existing offset/scale to qrBox
      const box = offsetScaleToQrBox({
        qrScale,
        qrOffsetX,
        qrOffsetY,
        placeholderBox: labelMeta.placeholderBox,
      });
      setQrBox(box);
    }
  }, [labelMeta, qrScale, qrOffsetX, qrOffsetY]);

  const handlePreview = async () => {
    setIsOpen(true);
    await fetchVersionData();
    await loadPreview();
  };

  const fetchVersionData = async () => {
    try {
      const response = await fetch(`/api/labels/versions/${versionId}`);
      if (response.ok) {
        const version = await response.json();
        
        // QR Settings
        const newQrScale = version.qrScale ?? 1.0;
        const newQrOffsetX = version.qrOffsetX ?? 0;
        const newQrOffsetY = version.qrOffsetY ?? 0;
        
        setQrScale(newQrScale);
        setQrOffsetX(newQrOffsetX);
        setQrOffsetY(newQrOffsetY);
        setSavedQrScale(newQrScale);
        setSavedQrOffsetX(newQrOffsetX);
        setSavedQrOffsetY(newQrOffsetY);

        // Canvas Settings
        const newContentScale = version.contentScale ?? 1.0;
        const newContentOffsetX = version.contentOffsetX ?? 0;
        const newContentOffsetY = version.contentOffsetY ?? 0;

        setContentScale(newContentScale);
        setContentOffsetX(newContentOffsetX);
        setContentOffsetY(newContentOffsetY);
        setSavedContentScale(newContentScale);
        setSavedContentOffsetX(newContentOffsetX);
        setSavedContentOffsetY(newContentOffsetY);

        // Label Size Settings
        if (version.labelWidthIn && version.labelHeightIn) {
          setLabelSizeOverride(true);
          setLabelWidthIn(version.labelWidthIn);
          setLabelHeightIn(version.labelHeightIn);
          setSavedLabelWidthIn(version.labelWidthIn);
          setSavedLabelHeightIn(version.labelHeightIn);
        } else {
          setLabelSizeOverride(false);
          setSavedLabelWidthIn(null);
          setSavedLabelHeightIn(null);
        }
      }
    } catch (err) {
      console.error('Failed to fetch version data:', err);
    }
  };

  const loadPreview = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    setSvgContent(null);
    setSheetMeta(null);

    try {
      const endpoint = previewMode === 'single' 
        ? '/api/labels/preview'
        : '/api/labels/preview-sheet';

      // Build request body with size override if enabled
      const baseBody = { 
        versionId, 
        qrScale, 
        qrOffsetX, 
        qrOffsetY,
        format: 'json' // Always request JSON for metadata
      };

      const body = previewMode === 'single'
        ? { 
            ...baseBody,
            ...(labelSizeOverride && { labelWidthIn, labelHeightIn }),
            contentOffsetX,
            contentOffsetY,
            contentScale
          }
        : { 
            ...baseBody, 
            quantity,
            ...(labelSizeOverride && { labelWidthIn, labelHeightIn }),
            contentOffsetX,
            contentOffsetY,
            contentScale
          };

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || errorData.error || 'Failed to load preview');
      }

      // Parse JSON response with metadata
      const data = await response.json();
      setSvgContent(data.svg);
      
      // Set label metadata
      const meta: LabelMetadata = previewMode === 'single' ? data.meta : data.labelMeta;
      setLabelMeta(meta);
      
      // Initialize native dimensions on first load
      if (nativeLabelWidthIn === null && meta) {
        setNativeLabelWidthIn(meta.widthIn);
        setNativeLabelHeightIn(meta.heightIn);
        // Initialize override values to native dimensions
        if (!labelSizeOverride) {
          setLabelWidthIn(meta.widthIn);
          setLabelHeightIn(meta.heightIn);
        }
      }

      if (previewMode === 'sheet' && data.sheetMeta) {
        setSheetMeta(data.sheetMeta);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to load preview');
    } finally {
      setIsLoading(false);
    }
  }, [previewMode, versionId, quantity, qrScale, qrOffsetX, qrOffsetY, labelSizeOverride, labelWidthIn, labelHeightIn, nativeLabelWidthIn, contentOffsetX, contentOffsetY, contentScale]);

  // Debounced preview update when position changes
  useEffect(() => {
    if (!isOpen) return;
    
    const timer = setTimeout(() => {
      loadPreview();
    }, 300);

    return () => clearTimeout(timer);
  }, [qrScale, qrOffsetX, qrOffsetY, contentOffsetX, contentOffsetY, contentScale, isOpen, loadPreview]);

  const handleModeChange = (mode: PreviewMode) => {
    setPreviewMode(mode);
  };

  const handleRefresh = () => {
    loadPreview();
  };

  const handleScaleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newScale = parseFloat(e.target.value);
    setQrScale(newScale);
  };

  // Nudge functions with configurable step
  const nudgeStep = 2; // SVG units per nudge

  const nudgeLeft = () => setQrOffsetX(prev => prev - nudgeStep);
  const nudgeRight = () => setQrOffsetX(prev => prev + nudgeStep);
  const nudgeUp = () => setQrOffsetY(prev => prev - nudgeStep);
  const nudgeDown = () => setQrOffsetY(prev => prev + nudgeStep);

  // Content nudge functions
  const contentNudgeStep = useFineControls ? 0.01 : 0.05; // inches
  const contentNudgeLeft = () => setContentOffsetX(prev => parseFloat((prev - contentNudgeStep).toFixed(3)));
  const contentNudgeRight = () => setContentOffsetX(prev => parseFloat((prev + contentNudgeStep).toFixed(3)));
  const contentNudgeUp = () => setContentOffsetY(prev => parseFloat((prev - contentNudgeStep).toFixed(3)));
  const contentNudgeDown = () => setContentOffsetY(prev => parseFloat((prev + contentNudgeStep).toFixed(3)));
  const resetContentOffset = () => { 
    setContentOffsetX(0); 
    setContentOffsetY(0);
    setContentScale(1.0);
  };

  const handleSavePosition = async () => {
    setIsSaving(true);
    setError(null);

    try {
      const body: any = { 
        qrScale, 
        qrOffsetX, 
        qrOffsetY,
        contentScale,
        contentOffsetX,
        contentOffsetY
      };

      if (labelSizeOverride) {
        body.labelWidthIn = labelWidthIn;
        body.labelHeightIn = labelHeightIn;
      }

      const response = await fetch(`/api/labels/versions/${versionId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || errorData.error || 'Failed to save position');
      }

      setSavedQrScale(qrScale);
      setSavedQrOffsetX(qrOffsetX);
      setSavedQrOffsetY(qrOffsetY);
      
      setSavedContentScale(contentScale);
      setSavedContentOffsetX(contentOffsetX);
      setSavedContentOffsetY(contentOffsetY);

      if (labelSizeOverride) {
        setSavedLabelWidthIn(labelWidthIn);
        setSavedLabelHeightIn(labelHeightIn);
      } else {
        setSavedLabelWidthIn(null);
        setSavedLabelHeightIn(null);
      }

      setHasUnsavedChanges(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save');
    } finally {
      setIsSaving(false);
    }
  };

  const handleResetPosition = () => {
    setQrScale(savedQrScale);
    setQrOffsetX(savedQrOffsetX);
    setQrOffsetY(savedQrOffsetY);
    
    setContentScale(savedContentScale);
    setContentOffsetX(savedContentOffsetX);
    setContentOffsetY(savedContentOffsetY);

    if (savedLabelWidthIn !== null && savedLabelHeightIn !== null) {
      setLabelSizeOverride(true);
      setLabelWidthIn(savedLabelWidthIn);
      setLabelHeightIn(savedLabelHeightIn);
    } else {
      // Revert to native if no saved override, or keep existing override disabled
      // Better to check if we were overriding
      if (labelSizeOverride && savedLabelWidthIn === null) {
        setLabelSizeOverride(false);
        if (nativeLabelWidthIn && nativeLabelHeightIn) {
          setLabelWidthIn(nativeLabelWidthIn);
          setLabelHeightIn(nativeLabelHeightIn);
        }
      }
    }
  };

  // Reset QR to default position (placeholder position or auto-generated default)
  const handleResetQrToDefault = () => {
    setQrScale(1.0);
    setQrOffsetX(0);
    setQrOffsetY(0);
    // Reset qrBox to suggested placement
    if (labelMeta) {
      const suggested = suggestQrPlacement({
        labelWidthIn: labelMeta.widthIn,
        labelHeightIn: labelMeta.heightIn,
      });
      setQrBox(suggested);
    }
  };

  // Handle qrBox changes from overlay (update offset/scale for API)
  const handleQrBoxChange = useCallback((newBox: QrBoxPosition) => {
    setQrBox(newBox);
    
    // Convert to offset/scale for API calls
    if (labelMeta?.placeholderBox) {
      const { qrScale: newScale, qrOffsetX: newOffsetX, qrOffsetY: newOffsetY } = qrBoxToOffsetScale({
        qrBox: newBox,
        placeholderBox: labelMeta.placeholderBox,
      });
      setQrScale(newScale);
      setQrOffsetX(newOffsetX);
      setQrOffsetY(newOffsetY);
    }
  }, [labelMeta]);

  // Maximize QR (safe) - centers QR at maximum size with margin
  const handleMaximizeQr = () => {
    if (!labelMeta) return;
    
    const maxBox = calculateMaxQrSize({
      labelWidthIn: labelMeta.widthIn,
      labelHeightIn: labelMeta.heightIn,
      marginIn: 0.1,
    });
    handleQrBoxChange(maxBox);
  };

  // Suggest better placement based on dead-space detection
  const handleSuggestPlacement = () => {
    if (!labelMeta || !qrBox) return;
    
    const regions = findLargestEmptyRegion({
      labelWidthIn: labelMeta.widthIn,
      labelHeightIn: labelMeta.heightIn,
      qrSizeIn: qrBox.widthIn,
    });
    
    // Use the first (best) suggestion
    if (regions.length > 0) {
      handleQrBoxChange({
        ...qrBox,
        xIn: regions[0].region.xIn,
        yIn: regions[0].region.yIn,
      });
    }
  };

  // Get suggested regions for visual overlay
  const suggestedRegions = labelMeta && qrBox
    ? findLargestEmptyRegion({
        labelWidthIn: labelMeta.widthIn,
        labelHeightIn: labelMeta.heightIn,
        qrSizeIn: qrBox.widthIn,
      })
    : [];

  // Toggle label size override
  const handleToggleSizeOverride = () => {
    if (!labelSizeOverride && nativeLabelWidthIn !== null && nativeLabelHeightIn !== null) {
      // When enabling, initialize to native dimensions
      setLabelWidthIn(nativeLabelWidthIn);
      setLabelHeightIn(nativeLabelHeightIn);
    }
    setLabelSizeOverride(!labelSizeOverride);
  };

  // Reset label size to native dimensions
  const handleResetLabelSize = () => {
    if (nativeLabelWidthIn !== null && nativeLabelHeightIn !== null) {
      setLabelWidthIn(nativeLabelWidthIn);
      setLabelHeightIn(nativeLabelHeightIn);
    }
  };

  // Get display value based on unit
  const getDisplayWidth = () => labelSizeUnit === 'in' ? labelWidthIn : inToMm(labelWidthIn);
  const getDisplayHeight = () => labelSizeUnit === 'in' ? labelHeightIn : inToMm(labelHeightIn);

  // Handle dimension input changes
  const handleWidthChange = (value: number) => {
    const inchValue = labelSizeUnit === 'in' ? value : mmToIn(value);
    setLabelWidthIn(Math.max(0.5, Math.min(20, inchValue)));
  };

  const handleHeightChange = (value: number) => {
    const inchValue = labelSizeUnit === 'in' ? value : mmToIn(value);
    setLabelHeightIn(Math.max(0.5, Math.min(20, inchValue)));
  };

  // State for sidebar collapse
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  
  // Zoom state for preview display
  const [zoom, setZoom] = useState(100);
  const previewAreaRef = useRef<HTMLDivElement>(null);
  
  // Fit to window calculation
  const handleFitToWindow = useCallback(() => {
    if (!previewAreaRef.current || !labelMeta) return;
    
    const container = previewAreaRef.current;
    const availableWidth = container.clientWidth - 80; // padding
    const availableHeight = container.clientHeight - 80;
    
    // Convert label size to pixels (assuming 96 DPI for display)
    const labelWidthPx = labelMeta.widthIn * 96;
    const labelHeightPx = labelMeta.heightIn * 96;
    
    // Calculate zoom to fit
    const zoomToFitWidth = (availableWidth / labelWidthPx) * 100;
    const zoomToFitHeight = (availableHeight / labelHeightPx) * 100;
    const fitZoom = Math.min(zoomToFitWidth, zoomToFitHeight, 400); // Cap at 400%
    
    setZoom(Math.round(fitZoom));
  }, [labelMeta]);

  // Auto-fit on first load only (not when user changes zoom)
  const hasAutoFittedRef = useRef(false);
  useEffect(() => {
    if (svgContent && labelMeta && !hasAutoFittedRef.current) {
      hasAutoFittedRef.current = true;
      // Small delay to ensure container is measured
      const timer = setTimeout(handleFitToWindow, 100);
      return () => clearTimeout(timer);
    }
  }, [svgContent, labelMeta, handleFitToWindow]);

  return (
    <>
      <button
        onClick={handlePreview}
        className="text-blue-600 hover:text-blue-900 font-medium"
      >
        Preview
      </button>

      {/* Full-Screen Preview Modal */}
      {isOpen && (
        <div className="fixed inset-0 z-50 bg-gray-900">
          {/* Header Bar */}
          <div className="h-12 bg-gray-800 border-b border-gray-700 flex items-center justify-between px-4">
            <div className="flex items-center gap-4">
              <h3 className="text-white font-medium">Label Preview</h3>
              <span className="text-gray-400 text-sm">{entityType}</span>

                {/* Preview Mode Toggle */}
              <div className="flex rounded-md overflow-hidden border border-gray-600">
                    <button
                      type="button"
                      onClick={() => handleModeChange('single')}
                  className={`px-3 py-1 text-xs font-medium transition-colors ${
                        previewMode === 'single'
                      ? 'bg-blue-600 text-white'
                      : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                      }`}
                    >
                  Single
                    </button>
                    <button
                      type="button"
                      onClick={() => handleModeChange('sheet')}
                  className={`px-3 py-1 text-xs font-medium transition-colors ${
                        previewMode === 'sheet'
                      ? 'bg-blue-600 text-white'
                      : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                      }`}
                    >
                  Sheet
                    </button>
                  </div>

                  {/* Sheet Options */}
                  {previewMode === 'sheet' && (
                <div className="flex items-center gap-2">
                        <input
                          type="number"
                          min={1}
                          max={1000}
                          value={quantity}
                          onChange={(e) => setQuantity(Math.min(1000, Math.max(1, parseInt(e.target.value) || 1)))}
                    className="w-16 px-2 py-1 text-xs bg-gray-700 border border-gray-600 rounded text-white"
                        />
                      {sheetMeta && (
                    <span className="text-xs text-gray-400">
                      {sheetMeta.columns}×{sheetMeta.rows} · {sheetMeta.perSheet}/sheet
                    </span>
                  )}
                        </div>
                      )}
                    </div>

            <div className="flex items-center gap-3">
              {/* Zoom Controls */}
              <div className="flex items-center gap-1 bg-gray-700 rounded px-2 py-1">
                <button
                  type="button"
                  onClick={() => setZoom(z => Math.max(25, z - 25))}
                  className="w-6 h-6 flex items-center justify-center text-gray-300 hover:text-white"
                  title="Zoom out"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 12H4" />
                  </svg>
                </button>
                <span className="text-xs text-gray-300 w-12 text-center font-mono">{zoom}%</span>
                <button
                  type="button"
                  onClick={() => setZoom(z => Math.min(400, z + 25))}
                  className="w-6 h-6 flex items-center justify-center text-gray-300 hover:text-white"
                  title="Zoom in"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                </button>
                <button
                  type="button"
                  onClick={handleFitToWindow}
                  className="ml-1 px-2 py-0.5 text-xs text-gray-300 hover:text-white border-l border-gray-600"
                  title="Fit to window"
                >
                  Fit
                </button>
                <button
                  type="button"
                  onClick={() => setZoom(100)}
                  className="px-2 py-0.5 text-xs text-gray-300 hover:text-white"
                  title="Reset to 100%"
                >
                  1:1
                </button>
              </div>

              {hasUnsavedChanges && (
                <span className="text-xs text-amber-400">● Unsaved</span>
              )}
                  <button
                    type="button"
                    onClick={handleRefresh}
                    disabled={isLoading}
                className="px-3 py-1 text-xs font-medium text-blue-400 hover:text-blue-300 disabled:opacity-50"
                  >
                {isLoading ? '...' : '↻ Refresh'}
              </button>
              <button
                onClick={() => setIsOpen(false)}
                className="p-1 text-gray-400 hover:text-white rounded"
              >
                <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                  </button>
                </div>
          </div>

          {/* Main Content - Sidebar + Preview */}
          <div className="flex h-[calc(100vh-48px)]">
            {/* Collapsible Sidebar */}
            <div className={`bg-gray-800 border-r border-gray-700 flex flex-col transition-all duration-200 ${
              sidebarCollapsed ? 'w-10' : 'w-72'
            }`}>
              {/* Collapse Toggle */}
              <button
                onClick={() => setSidebarCollapsed(!sidebarCollapsed)}
                className="h-8 flex items-center justify-center text-gray-400 hover:text-white border-b border-gray-700"
              >
                <svg className={`w-4 h-4 transition-transform ${sidebarCollapsed ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
              </button>

              {!sidebarCollapsed && (
                <div className="flex-1 overflow-y-auto p-3 space-y-3">
                  {/* QR Size Control */}
                  <div className="bg-gray-750 rounded-lg p-3">
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-xs font-medium text-gray-300">QR Size</label>
                      <span className="text-xs font-mono text-blue-400">
                        {qrBox ? `${qrBox.widthIn.toFixed(2)}in` : `${Math.round(qrScale * 100)}%`}
                        </span>
                      </div>
                      <input
                        type="range"
                        min="0.1"
                        max="1.5"
                        step="0.05"
                        value={qrScale}
                        onChange={handleScaleChange}
                      className="w-full h-1.5 bg-gray-600 rounded-lg appearance-none cursor-pointer accent-blue-500"
                      />
                    <div className="flex gap-1 mt-2">
                      <button
                        type="button"
                        onClick={handleMaximizeQr}
                        className="flex-1 px-2 py-1.5 text-xs font-medium text-blue-400 bg-blue-900/30 border border-blue-800 rounded hover:bg-blue-900/50"
                      >
                        📐 Max
                      </button>
                      <button
                        type="button"
                        onClick={handleSuggestPlacement}
                        className="flex-1 px-2 py-1.5 text-xs font-medium text-green-400 bg-green-900/30 border border-green-800 rounded hover:bg-green-900/50"
                      >
                        💡 Suggest
                      </button>
                    </div>
                  </div>

                  {/* Position Controls */}
                  <div className="bg-gray-750 rounded-lg p-3">
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-xs font-medium text-gray-300">Position</label>
                      <span className="text-xs font-mono text-gray-400">
                        {qrBox ? `${qrBox.xIn.toFixed(2)}, ${qrBox.yIn.toFixed(2)}` : '0, 0'}
                      </span>
                    </div>
                    <div className="flex items-center justify-center">
                      <div className="grid grid-cols-3 gap-0.5">
                        <div />
                        <button type="button" onClick={nudgeUp} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" /></svg>
                        </button>
                        <div />
                        <button type="button" onClick={nudgeLeft} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
                        </button>
                        <button type="button" onClick={() => { setQrOffsetX(0); setQrOffsetY(0); }} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300 text-xs">⊙</button>
                        <button type="button" onClick={nudgeRight} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                        </button>
                        <div />
                        <button type="button" onClick={nudgeDown} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                        </button>
                        <div />
                      </div>
                    </div>
                    <label className="flex items-center gap-2 mt-2 cursor-pointer justify-center">
                      <input
                        type="checkbox"
                        checked={showSuggestions}
                        onChange={(e) => setShowSuggestions(e.target.checked)}
                        className="rounded border-gray-600 bg-gray-700 text-green-500 focus:ring-green-500 focus:ring-offset-gray-800"
                      />
                      <span className="text-xs text-gray-400">Show zones</span>
                        </label>
                      </div>

                  {/* Label Size Override */}
                  <div className="bg-gray-750 rounded-lg p-3">
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-xs font-medium text-gray-300">Label Size</label>
                          <button
                            type="button"
                        onClick={handleToggleSizeOverride}
                        className={`relative w-8 h-4 rounded-full transition-colors ${labelSizeOverride ? 'bg-amber-600' : 'bg-gray-600'}`}
                          >
                        <span className={`absolute top-0.5 left-0.5 w-3 h-3 bg-white rounded-full transition-transform ${labelSizeOverride ? 'translate-x-4' : ''}`} />
                          </button>
                    </div>
                    {labelSizeOverride && (
                      <div className="space-y-2">
                        <div className="flex gap-2">
                          <div className="flex-1">
                            <input
                              type="number"
                              step="0.125"
                              value={getDisplayWidth().toFixed(3)}
                              onChange={(e) => handleWidthChange(parseFloat(e.target.value) || 0)}
                              className="w-full px-2 py-1 text-xs bg-gray-700 border border-gray-600 rounded text-white"
                            />
                          </div>
                          <span className="text-gray-500 self-center">×</span>
                          <div className="flex-1">
                            <input
                              type="number"
                              step="0.125"
                              value={getDisplayHeight().toFixed(3)}
                              onChange={(e) => handleHeightChange(parseFloat(e.target.value) || 0)}
                              className="w-full px-2 py-1 text-xs bg-gray-700 border border-gray-600 rounded text-white"
                            />
                          </div>
                          <select
                            value={labelSizeUnit}
                            onChange={(e) => setLabelSizeUnit(e.target.value as 'in' | 'mm')}
                            className="px-1 py-1 text-xs bg-gray-700 border border-gray-600 rounded text-white"
                          >
                            <option value="in">in</option>
                            <option value="mm">mm</option>
                          </select>
                        </div>
                        {nativeLabelWidthIn && nativeLabelHeightIn && (
                          <p className="text-xs text-gray-500">
                            Native: {nativeLabelWidthIn.toFixed(2)}×{nativeLabelHeightIn.toFixed(2)}in
                          </p>
                        )}
                      </div>
                    )}
                    {!labelSizeOverride && nativeLabelWidthIn && nativeLabelHeightIn && (
                      <p className="text-xs text-gray-500">
                        {nativeLabelWidthIn.toFixed(2)} × {nativeLabelHeightIn.toFixed(2)} in
                        </p>
                      )}
                    </div>

                  {/* Content Position Controls */}
                  <div className="bg-gray-750 rounded-lg p-3">
                    <div className="flex items-center justify-between mb-3">
                      <label className="text-xs font-medium text-gray-300">Canvas Adjustment</label>
                      <button
                        type="button"
                        onClick={() => setUseFineControls(!useFineControls)}
                        className={`text-[10px] px-2 py-0.5 rounded border ${
                          useFineControls 
                            ? 'bg-blue-900/30 text-blue-400 border-blue-800' 
                            : 'bg-gray-700 text-gray-400 border-gray-600'
                        }`}
                      >
                        {useFineControls ? 'Fine' : 'Coarse'}
                      </button>
                    </div>

                    {/* Scale Control */}
                    <div className="mb-3">
                      <div className="flex justify-between text-xs text-gray-400 mb-1">
                        <span>Scale</span>
                        <span>{Math.round(contentScale * 100)}%</span>
                      </div>
                      <input
                        type="range"
                        min="0.5"
                        max="1.5"
                        step="0.01"
                        value={contentScale}
                        onChange={(e) => setContentScale(parseFloat(e.target.value))}
                        className="w-full h-1.5 bg-gray-600 rounded-lg appearance-none cursor-pointer accent-blue-500"
                      />
                    </div>

                    {/* Position Nudge */}
                    <div className="flex items-center justify-center">
                      <div className="grid grid-cols-3 gap-0.5">
                        <div />
                        <button type="button" onClick={contentNudgeUp} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" /></svg>
                        </button>
                        <div />
                        <button type="button" onClick={contentNudgeLeft} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
                        </button>
                        <button type="button" onClick={resetContentOffset} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300 text-xs" title="Reset All">⊙</button>
                        <button type="button" onClick={contentNudgeRight} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                        </button>
                        <div />
                        <button type="button" onClick={contentNudgeDown} className="w-7 h-7 flex items-center justify-center bg-gray-700 border border-gray-600 rounded hover:bg-gray-600 text-gray-300">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                        </button>
                        <div />
                      </div>
                    </div>
                    <div className="text-center mt-1">
                      <span className="text-[10px] font-mono text-gray-500">
                        {contentOffsetX.toFixed(2)}, {contentOffsetY.toFixed(2)}
                      </span>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="space-y-2">
                    <button
                      type="button"
                      onClick={handleSavePosition}
                      disabled={!hasUnsavedChanges || isSaving}
                      className={`w-full px-3 py-2 text-sm font-medium rounded transition-colors ${
                        hasUnsavedChanges
                          ? 'bg-green-600 text-white hover:bg-green-700'
                          : 'bg-gray-700 text-gray-500 cursor-not-allowed'
                      }`}
                    >
                      {isSaving ? 'Saving...' : 'Save Position'}
                    </button>
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={handleResetQrToDefault}
                        className="flex-1 px-2 py-1.5 text-xs text-gray-400 bg-gray-700 border border-gray-600 rounded hover:bg-gray-600"
                      >
                        Reset Default
                      </button>
                      {hasUnsavedChanges && (
                        <button
                          type="button"
                          onClick={handleResetPosition}
                          className="flex-1 px-2 py-1.5 text-xs text-gray-400 bg-gray-700 border border-gray-600 rounded hover:bg-gray-600"
                        >
                          Revert
                        </button>
                      )}
                    </div>
                  </div>

                  {/* Info */}
                  <div className="text-xs text-gray-500 p-2 bg-gray-900/50 rounded">
                    <p>💡 Drag the blue box to move QR</p>
                    <p className="mt-1">↘ Drag corner to resize</p>
                  </div>
                </div>
              )}
                </div>

            {/* Preview Area - Takes remaining space */}
            <div 
              ref={previewAreaRef}
              className="flex-1 bg-gray-950 flex items-center justify-center overflow-auto"
            >
                  {isLoading ? (
                    <div className="text-center">
                  <svg className="animate-spin h-10 w-10 text-blue-500 mx-auto" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                      </svg>
                  <p className="mt-3 text-sm text-gray-400">Loading preview...</p>
                    </div>
                  ) : error ? (
                <div className="text-center max-w-md">
                  <svg className="h-16 w-16 text-red-500 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                      </svg>
                  <p className="text-lg font-medium text-red-400 mb-2">Preview Error</p>
                  <p className="text-sm text-gray-400">{error}</p>
                    </div>
                  ) : svgContent ? (
                <div 
                  className="relative p-10"
                  style={{ 
                    transform: `scale(${zoom / 100})`,
                    transformOrigin: 'center center',
                  }}
                >
                  
                  {/* SVG Preview with QR Overlay */}
                  <div 
                    ref={previewContainerRef}
                    className="relative bg-white rounded-lg shadow-2xl"
                    style={{
                      width: labelMeta ? `${labelMeta.widthIn}in` : 'auto',
                      height: labelMeta ? `${labelMeta.heightIn}in` : 'auto',
                    }}
                  >
                    <div 
                        dangerouslySetInnerHTML={{ __html: svgContent }}
                      className="w-full h-full [&>svg]:w-full [&>svg]:h-full"
                    />
                    
                    {/* QR Box Overlay - only for single label mode */}
                    {previewMode === 'single' && labelMeta && qrBox && containerDimensions.width > 0 && (
                      <QRBoxOverlay
                        qrBox={qrBox}
                        labelWidthIn={labelMeta.widthIn}
                        labelHeightIn={labelMeta.heightIn}
                        containerWidth={containerDimensions.width}
                        containerHeight={containerDimensions.height}
                        onBoxChange={handleQrBoxChange}
                        suggestedRegions={suggestedRegions}
                        showSuggestions={showSuggestions}
                        zoomScale={zoom / 100}
                      />
                    )}
                  </div>
                </div>
                  ) : (
                    <div className="text-center text-gray-500">
                      <p>Click Refresh to load preview</p>
                    </div>
                  )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
