import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth/auth';
import { renderLetterSheetPreview } from '@/lib/services/labelService';
import { handleApiError } from '@/lib/utils/errors';

/**
 * POST /api/labels/preview-sheet
 * 
 * Render a letter-size sheet preview with metadata
 * 
 * Request body:
 * - versionId: string (required)
 * - quantity: number (default: 1)
 * - qrScale?: number (0.1-1.5)
 * - qrOffsetX?: number
 * - qrOffsetY?: number
 * - labelWidthIn?: number (optional size override, render-time only)
 * - labelHeightIn?: number (optional size override, render-time only)
 * - format?: 'json' | 'svg' (default: 'json')
 * 
 * Response (format=json):
 * {
 *   svg: string,
 *   sheetMeta: { columns, rows, perSheet, rotationUsed, totalSheets },
 *   labelMeta: { widthIn, heightIn, hasPlaceholder, placeholderBox, isAutoGenerated }
 * }
 * 
 * Response (format=svg):
 * Raw SVG content with X-Label-* headers for metadata
 * 
 * Note: Label size override is treated as a layout instruction applied at render time.
 * The original SVG remains unchanged in storage.
 */
export async function POST(req: Request) {
  try {
    const session = await auth();
    
    if (!session || !session.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await req.json();
    const { versionId, quantity, qrScale, qrOffsetX, qrOffsetY, labelWidthIn, labelHeightIn, contentOffsetX, contentOffsetY, contentScale, format = 'json' } = body;

    if (!versionId) {
      return NextResponse.json(
        { error: 'versionId is required' },
        { status: 400 }
      );
    }

    // Parse QR position overrides
    let parsedQrScale: number | undefined;
    if (qrScale !== undefined) {
      const scale = parseFloat(qrScale);
      if (!isNaN(scale) && scale >= 0.1 && scale <= 1.5) {
        parsedQrScale = scale;
      }
    }

    let parsedOffsetX: number | undefined;
    if (qrOffsetX !== undefined) {
      const x = parseFloat(qrOffsetX);
      if (!isNaN(x)) parsedOffsetX = x;
    }

    let parsedOffsetY: number | undefined;
    if (qrOffsetY !== undefined) {
      const y = parseFloat(qrOffsetY);
      if (!isNaN(y)) parsedOffsetY = y;
    }

    // Parse label size overrides (render-time only, non-destructive)
    let parsedLabelWidthIn: number | undefined;
    if (labelWidthIn !== undefined) {
      const w = parseFloat(labelWidthIn);
      if (!isNaN(w) && w > 0 && w <= 20) parsedLabelWidthIn = w;
    }

    let parsedLabelHeightIn: number | undefined;
    if (labelHeightIn !== undefined) {
      const h = parseFloat(labelHeightIn);
      if (!isNaN(h) && h > 0 && h <= 20) parsedLabelHeightIn = h;
    }

    // Parse content placement overrides
    let parsedContentOffsetX: number | undefined;
    if (contentOffsetX !== undefined) {
      const x = parseFloat(contentOffsetX);
      if (!isNaN(x)) parsedContentOffsetX = x;
    }

    let parsedContentOffsetY: number | undefined;
    if (contentOffsetY !== undefined) {
      const y = parseFloat(contentOffsetY);
      if (!isNaN(y)) parsedContentOffsetY = y;
    }

    let parsedContentScale: number | undefined;
    if (contentScale !== undefined) {
      const s = parseFloat(contentScale);
      if (!isNaN(s) && s > 0) parsedContentScale = s;
    }

    const result = await renderLetterSheetPreview({
      versionId,
      quantity: parseInt(quantity, 10) || 1,
      qrScale: parsedQrScale,
      qrOffsetX: parsedOffsetX,
      qrOffsetY: parsedOffsetY,
      labelWidthIn: parsedLabelWidthIn,
      labelHeightIn: parsedLabelHeightIn,
      contentOffsetX: parsedContentOffsetX,
      contentOffsetY: parsedContentOffsetY,
      contentScale: parsedContentScale
    });

    // Support legacy format=svg for backwards compatibility
    if (format === 'svg') {
    return new NextResponse(result.svg, {
      headers: {
        'Content-Type': 'image/svg+xml',
        'X-Label-Columns': String(result.meta.columns),
        'X-Label-Rows': String(result.meta.rows),
        'X-Label-Per-Sheet': String(result.meta.perSheet),
        'X-Label-Rotation-Used': String(result.meta.rotationUsed),
          'X-Label-Total-Sheets': String(result.meta.totalSheets),
          'X-Label-Width-In': String(result.labelMeta.widthIn),
          'X-Label-Height-In': String(result.labelMeta.heightIn),
          'X-Label-Has-Placeholder': String(result.labelMeta.hasPlaceholder),
          'X-Label-Auto-Generated': String(result.labelMeta.isAutoGenerated)
        }
      });
    }

    // Default: return JSON with SVG and all metadata
    return NextResponse.json({
      svg: result.svg,
      sheetMeta: result.meta,
      labelMeta: result.labelMeta
    });
  } catch (error) {
    return handleApiError(error);
  }
}

